{
 "title": "The Four Golden Signals 2",
 "tags": [
  "demo",
  "usecase",
  "featured-usecase"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "The Four Golden Signals",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard is an example of a best practice called\n\"The Four Golden Signals\":  Latency, Traffic, Errors, and Saturation.\n\n[Click here](https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/best-practices/) for more best practices in our documentation"
   }
  },
  {
   "title": "LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "node_load5",
     "legendFormat": "__auto",
     "target": "alias(movingAverage(statsd.fakesite.timers.ads_timer.upper_50, 5), 'OK')"
    },
    {
     "target": "alias(movingAverage(statsd.fakesite.timers.ads_timer.upper_25, 5), 'Errors')"
    }
   ]
  },
  {
   "title": "TRAFFIC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total",
     "legendFormat": "__auto",
     "target": "alias(scaleToSeconds(apps.backend.backend_01.counters.requests.count, 1), 'Requests/s')"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_disk_io_time_seconds_total",
     "legendFormat": "__auto",
     "target": "aliasByNode(apps.fakesite.web_server_01.counters.request_status.{code_500,code_400}.count, 5)"
    }
   ]
  },
  {
   "title": "SATURATION",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes",
     "legendFormat": "__auto",
     "target": "alias(scale(apps.fakesite.web_server_01.counters.request_status.code_200.count, 0.3), 'DB CPU')"
    }
   ]
  }
 ]
}